name: thanks

on:
    issues:
        types: [opened]
    workflow_dispatch: # manual

jobs:
    say-thanks:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - uses: actions/github-script@v7
              id: issue_Script
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    const issue_number = context.issue.number || 2;
                    console.log('issuee_number:', issue_number);
                    
                    const owner = context.repo.owner;
                    const repo = context.repo.repo;

                    //look up issue info
                    const issue = await github.rest.issues.get({
                        owner,
                        repo,
                        issue_number,
                    });
                    console.log('issue info:', issue);

                    // create comment thanking contributor
                    const comment = await github.rest.issues.createComment({
                        owner,
                        repo,
                        issue_number,
                        body: `Thanks for opening this issue, @${issue.data.user.login}! We will look into it as soon as we can.`
                    });

                    // auto label the issue as "triage needed"
                    await github.rest.issues.addLabels({
                        owner,
                        repo,
                        issue_number,
                        labels: ['todo-review']
                    });

                    // make comment id available to subsequent steps
                    return comment.data.id;
            - run: echo "Comment ID:${{steps.issue_Script.outputs.result}}"